package springExample.repository;

import org.springframework.data.repository.CrudRepository;
import springExample.model.Expense;

//repository methods autogenerated
public interface ExpenseCrudRepository extends CrudRepository<Expense, Long> {
}
