apiVersion: v1
kind: Pod
metadata:
  name: mypod
  labels:
    env: dev
spec:
  containers:
    - name: basic-api
      image: basic-api
      imagePullPolicy: IfNotPresent
      ports:
      - containerPort: 8080
      resources:
        request: #min requested resources
          memory: "128Mi" #128 mebibytes
          cpu: "250m" #0.25 cpu core
        limits: #max used resources
          memory: "256Mi" #256 mebibytes
          cpu: "500m" #0.5 cpu core
