apiVersion: v1
kind: Pod
metadata:
  name: mypod
  namespace: test #define namespace of the pod
  labels:
    env: dev
spec:
  containers:
    - name: basic-api
      image: basic-api
      imagePullPolicy: IfNotPresent
      ports:
      - containerPort: 8080