apiVersion: v1
kind: Service
metadata:
  name: producerservice
spec:
  selector:
    app: producerpod
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080


---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: producerdeployment
spec:
  selector:
    matchLabels:
      app: producerpod
  replicas: 1
  template:
    metadata:
      labels:
        app: producerpod
    spec:
      containers:
        - name:  basic-api
          image: basic-api
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: config
data:
  #same namespace, i can omit namespace or cluster name in service url
  application.yml: |
    HELLO: http://producerservice:8080

---

apiVersion: v1
kind: Service
metadata:
  name: consumerservice
spec:
  selector:
    app: consumerpod
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080


---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumerdeployment
spec:
  selector:
    matchLabels:
      app: consumerpod
  replicas: 1
  template:
    metadata:
      labels:
        app: consumerpod
    spec:
      containers:
        - name:  basic-api
          image: basic-api
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          volumeMounts:
            - mountPath: "/config"
              name: application-properties
      volumes:
        - name: application-properties
          configMap:
            name: config