[project]
name = "a2a"
version = "0.1.0"
description = "a2a example"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "a2a-sdk>=0.3.0",
    "starlette>=0.46.2",
    "uvicorn>=0.34.2",
    "sse-starlette>=2.3.5",
    "starlette>=0.46.2",
]
