pipeline {
    agent any

    /* define external input to the pipeline */
    parameters {
        string(name: 'myparan', defaultValue: 'Hello', description: 'How should I greet the world?')
    }

    stages {
        stage('Build') {
            steps {
                echo "Building ${env.BUILD_ID} ${params.myparam}"
            }
        }
        stage('Test') {
            steps {
                echo "Testing ${env.BUILD_ID}"
            }
        }
        stage('Deploy') {
            steps {
                echo "Deploying ${env.BUILD_ID}"
            }
        }
    }
}
