package testExample.respository;

import org.springframework.data.repository.CrudRepository;
import testExample.model.Expense;

//repository methods autogenerated
public interface ExpenseCrudRepository extends CrudRepository<Expense, Long> {
}
