apiVersion: v1
kind: Service
metadata:
  name: myservice
spec:
  selector:
    app: mydeploy
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8080


---

apiVersion: v1
kind: Service
metadata:
  name: myservice-headless
spec:
  clusterIP: None #headless
  selector:
    app: mydeploy
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8080


---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydeployment
spec:
  selector:
    matchLabels:
      app: mydeploy
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: mydeploy
    spec:
      containers:
        - name:  basic-api
          image: basic-api
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080

---

#needed only for debugging
apiVersion: v1
kind: Pod
metadata:
  name: mypod
  labels:
    env: dev
spec:
  containers:
    - name: basic-api
      image: basic-api
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 8080